version: 0.0
os: windows

files: 
  - source: files
    destination: c:\\inetpub\\wwwroot

hooks:
  BeforeInstall:
    - location: scripts/webserver-stop.ps1
    - location: scripts/move-previous.ps1
  AfterInstall:
    - location: scripts/webserver-start.ps1
