version: 0.0
os: linux

files: 
  - source: files
    destination: /var/www/html

permissions:
  - object: /var/www/html
    pattern: index.html
    owner: apache
    group: apache
    mode: 644
    type:
      - file
  - object: /var/www/html
    owner: apache
    group: apache
    mode: 755
    type:
      - directory

hooks:
  BeforeInstall:
    - location: scripts/webserver-stop.sh
    - location: scripts/move-previous.sh
  AfterInstall:
    - location: scripts/webserver-start.sh
